Enable the Response serialization to support multi-lang RPC-client (excluding the Exception serialization).
distkv-project/drpc pull request #45
Opened 2019-12-08 03:05 UTC by zhengrenjie

2019-12-08 04:26 UTC, zhengrenjie commented
Some bugs occur.

2019-12-08 14:47 UTC, jovany-wang requested changes
BTW, It's necessary to add an unit test for DstCodec

2019-12-08 14:47 UTC, jovany-wang commented on transport/src/main/java/com/distkv/drpc/codec/DstCodec.java
> +    System.out.println(Arrays.toString(data));
remove this.

2019-12-10 02:52 UTC, senyer approved these changes
Nice job!

2019-12-10 11:58 UTC, closed without merging