Benchmark prototype.
distkv-project/drpc pull request #50
Opened 2019-12-14 09:03 UTC by zhengrenjie

2019-12-14 15:15 UTC, jovany-wang reviewed
Thanks. LGTM without the minor comments.

2019-12-14 15:15 UTC, jovany-wang commented on benchmark/src/main/java/com/distkv/drpc/benchmark/common/common_pb.proto
> +syntax="proto3";
Do not define this file. Just put the context to `string_pb.proto` and rename `string_pb.proto` to `str.proto`

2019-12-14 15:15 UTC, jovany-wang commented on benchmark/src/main/java/com/distkv/drpc/benchmark/common/consumer/DubboHttpProcessHandler.java
> +package com.distkv.drpc.benchmark.common.consumer;
What's the purpose to use dubbo http process?

Does it mean we use dubbo rpc via HTTP?

2019-12-15 12:41 UTC, jovany-wang approved these changes

2019-12-15 12:42 UTC, jovany-wang requested changes
Put benchmark into test module as a package

2019-12-16 02:30 UTC, zhengrenjie commented
Closed.

2019-12-16 02:30 UTC, closed without merging