Prototype of drpc-benchmark.
distkv-project/drpc pull request #64
Opened 2019-12-21 13:47 UTC by zhengrenjie

2019-12-21 15:46 UTC, jovany-wang reviewed
`.DS_Store` shouldn't be checked in.

2019-12-21 15:46 UTC, jovany-wang commented on test/script/benchmark.bash
> +#!/usr/bin/env bash
rename to .sh

2019-12-21 15:46 UTC, jovany-wang commented on test/script/benchmark.bash
> +
Add a brief here to elaborate what this script is.

2019-12-21 15:46 UTC, jovany-wang commented on test/script/wrk.lua
> +done = function(summary, latency, requests)
Put the file and `benchmark.sh` to scripts/benchmark dir

2019-12-21 15:46 UTC, jovany-wang commented on test/src/main/resources/pb/benchmark.proto
> +syntax = "proto3";
rename the dir `test/src/main/resources/proto/benchmark.proto`

2019-12-21 15:46 UTC, jovany-wang commented on test/src/main/java/com/distkv/drpc/test/common/Constants.java
> +  public static final String TEST_CONTENT =
I think we should define some contents with different sizes, like 5bytes, 100 bytes, 10m etc:

static final byte[]  TEST_CONTENT_5_BYTES = new byte[5];

static final byte[]  TEST_CONTENT_100_BYTES = new byte[100];

...

And then refine the proto to:
```proto
Message Request {
repeated byte xxx;
}
```

2019-12-22 13:34 UTC, jovany-wang commented
Some conflicts were introduced.

2019-12-23 03:52 UTC, zhengrenjie commented
I have fixed.
Please check it again.

2019-12-23 03:53 UTC, zhengrenjie commented
> `.DS_Store` shouldn't be checked in.

2019-12-23 05:46 UTC, jovany-wang requested changes
will share you more info offline.

2019-12-23 09:27 UTC, zhengrenjie commented
Please check it again.
@jovany-wang

2019-12-23 11:40 UTC, jovany-wang approved these changes

2019-12-23 11:55 UTC, merged